export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const ADD_ERROR_MESSAGE = "ADD_ERROR_MESSAGE";
export const REMOVE_ERROR_MESSAGE = "REMOVE_ERROR_MESSAGE";
export const ADD_SUCCESS_MESSAGE = "ADD_SUCCESS_MESSAGE";
export const REMOVE_SUCCESS_MESSAGE = "REMOVE_SUCCESS_MESSAGE";

export const SAVE_USER = "SAVE_USER";
